### PR TITLE
Stop ignoring `D412` rule in the flake8 and precommit configurations

### PR DESCRIPTION
**Pull request by cidrblock**
Part of an ongoing effort to improve documentation for future contributors:

Clean-up was done in #651

This updates the .flake8 file to reflect those changes.

Additionally remove from pre-commit config, since this is the last occurance

(missed in #856 )

### CODE REVIEW

**Review by webknjaz — APPROVED** [review]

**Review by ssbarnea — APPROVED** [review]

**Review by ssbarnea — DISMISSED** [review]
Still present in https://github.com/ansible/ansible-navigator/blob/88e0d64981aa1899f22cf4e96727d34f9f0267c1/.pre-commit-config.yaml#L146

**Comment by webknjaz** [comment]
> Still present in

That's a different config and a different hook (which should probably be removed anyway because it is exactly the same as `flake8-docstrings`).
I don't think that this review is relevant to this PR as it specifically addresses flake8 violations and not other things.

**Comment by cidrblock** [comment]
> Still present in
> 
> https://github.com/ansible/ansible-navigator/blob/88e0d64981aa1899f22cf4e96727d34f9f0267c1/.pre-commit-config.yaml#L146

It's not clear to me why that is in pre-commit, and is generally not something I pay attention to.

If it can be removed, let's do that.

**Comment by webknjaz** [comment]
> If it can be removed (the entire entry), let's do that.

Yes, I think it's just a result of synching stuff across projects.

**Pull request merged**
