### PR TITLE
Add pytest-rerunfailures for tests seen as failing randomly

### PR DESCRIPTION
**Pull request by ssbarnea**

### CODE REVIEW

**Review by webknjaz — CHANGES_REQUESTED** [review]
Let's instead use a more integrated solution: https://pypi.org/p/pytest-rerunfailures / https://github.com/pytest-dev/pytest-rerunfailures. I saw it being used in the pip's CI and it's trusted.

**Comment by ssbarnea** [comment]
> Let's instead use a more integrated solution: [pypi.org/p/pytest-rerunfailures](https://pypi.org/p/pytest-rerunfailures) / [pytest-dev/pytest-rerunfailures](https://github.com/pytest-dev/pytest-rerunfailures). I saw it being used in the pip's CI and it's trusted.

I checked it and you are welcomed to repurpose this PR and use that plugin instead, it seems as a maintained one.

**Review by webknjaz — APPROVED** [review]
This should be good now but need to wait for CI.

**Review by ssbarnea — COMMENTED** [review]
I approve the new form but please do not merge until we have confirmation from zuul with 2-3 r-e-c-h-e-c-k-s

**Comment by cidrblock** [comment]
Do we still need this?

**Comment by ssbarnea** [comment]
I moved it to draft as to make it it clear that we need to wait until we have some tests randomly failing. Those that are in current PR are not longer doing this.

**Pull request closed without merging**
