### PR TITLE
update readme quickstart with correct filepath

### PR DESCRIPTION
**Pull request by thedoubl3j**
path to install location is incorrect. added 2 steps to properly start the install since the setup.py is at the top level and no longer housed in `ansible_navigator`. 

edit: rewrite install since location moved

### CODE REVIEW

**Comment by thedoubl3j** [comment]
@cidrblock can squash if preferred as well

**Comment by cidrblock** [comment]
Doesn't the `cd..` take you to the parent of the demo directory, so you would need to `pip install ./ansible-navigator`?

**Review by cidrblock — COMMENTED** [review]
the way it was written, the user would be left in the ansible-navigator_demo directory.....

**Comment by cidrblock** [comment]
Ah! The hyphen.... too many name changes, I'll come up with something simple

**Pull request closed without merging**
