### PR TITLE
Ensure tox configuration focuses on docstrings and developer experience

### PR DESCRIPTION
**Pull request by cidrblock**
No changes in this PR should effect the current enforced configuration or the outcome of developers/CI runs using `tox -e lint`

The goal of vetting has always been to both vet different tools, workflows and configurations.  Based on what we've learned I believe this configuration draws more attention on those linters actively being remediated.

This positions us to incrementally add new linters that are interesting, do the clean up and show the positive results, without boiling the ocean and over complicating the configuration prior to enforcing a new one.

Additionally, this should improve the developer experience by:
1) Making lint-candidates an all in one check prior to a PR
2) Allow for IDE feedback for the linters being vetting by install the python packages for the flake8 extentions being vetted.  

Changes:
- Limit configuration to only those linters actively being remediated
- Make lint-candidates an all-in-one tox entry that includes all checks
- Add flake8 extentions to test-requirements so the developer IDE can report on these
- Add flake-8 quotes to the enforced, since it passes green (other than one error fixed in this PR)
- Remove or enable checks that have file exceptions and caused "skip no files" in pre-commit
- Replace the deprecated check byte-order with fix byte-order

What does it look like?

image

```
(venv) x1 ➜  ansible-navigator git:(focus_on_docs) ✗ tox -qe lint           
Add trailing commas.....................................................................................Passed
Sort import statements using isort......................................................................Passed
black...................................................................................................Passed
Spell check with cspell................................................................................Skipped
Tabs remover............................................................................................Passed
trim trailing whitespace................................................................................Passed
check for merge conflicts...............................................................................Passed
fix end of files........................................................................................Passed
fix requirements.txt....................................................................................Passed
check for added large files.............................................................................Passed
fix utf-8 byte order marker.............................................................................Passed
check for case conflicts................................................................................Passed
check docstring is first................................................................................Passed
check json..............................................................................................Passed
check for broken symlinks...............................................................................Passed
check yaml..............................................................................................Passed
detect private key......................................................................................Passed
check python ast........................................................................................Passed
debug statements (python)...............................................................................Passed
markdownlint............................................................................................Passed
codespell...............................................................................................Passed
yamllint................................................................................................Passed
flake8..................................................................................................Passed
Help improve our developer documentation. Try "tox -e lint-candidates" (optional)......................Skipped
MyPy, for Python 3.10..................................................................................Skipped
MyPy, for Python 3.6....................................................................................Passed
pylint..................................................................................................Passed
______________________________________________________________________________ summary _______________________________________________________________________________
  lint: commands succeeded
  congratulations :)
```

```
(venv) x1 ➜  ansible-navigator git:(focus_on_docs) ✗ tox -qe lint-candidates
Add trailing commas.....................................................................................Passed
Sort import statements using isort......................................................................Passed
black...................................................................................................Passed
Spell check with cspell.................................................................................Passed
Tabs remover............................................................................................Passed
trim trailing whitespace................................................................................Passed
check for merge conflicts...............................................................................Passed
fix end of files........................................................................................Passed
fix requirements.txt....................................................................................Passed
check for added large files.............................................................................Passed
fix utf-8 byte order marker.............................................................................Passed
check for case conflicts................................................................................Passed
check docstring is first................................................................................Passed
check json..............................................................................................Passed
check for broken symlinks...............................................................................Passed
check yaml..............................................................................................Passed
detect private key......................................................................................Passed
check python ast........................................................................................Passed
debug statements (python)...............................................................................Passed
markdownlint............................................................................................Passed
codespell...............................................................................................Passed
yamllint................................................................................................Passed
flake8..................................................................................................Passed
Help improve our developer documentation. Try "tox -e lint-candidates" (optional).......................Passed
MyPy, for Python 3.10...................................................................................Passed
MyPy, for Python 3.6....................................................................................Passed
pylint..................................................................................................Passed
______________________________________________________________________________ summary _______________________________________________________________________________
  lint-candidates: commands succeeded
  congratulations :)
```

Note: Evidence of the effort to remediate the docstring errors reported by darglint and pydocstyle can be found here: https://github.com/ansible/ansible-navigator/pulls?q=is%3Apr+is%3Aclosed+%28D%2FDAR%29

### CODE REVIEW

**Comment by cidrblock** [comment]
I am approving this PR on behalf of @relrod as we discussed this in length over the past 2 weeks and I believe this represents the outcome of those conversations.

**Review by ssbarnea — APPROVED** [review]

**Comment by cidrblock** [comment]
@webknjaz Happy to iterate on this and slowly add back some of what was removed as things get cleaned up.  I do think we should introduce things 1 at a time as things are cleaned up though.

**Comment by webknjaz** [comment]
I wish people were as eager to remove *really* harmful things like black.

**Comment by cidrblock** [comment]
> I wish people were as eager to remove _really_ harmful things like black.

This PR has nothing to do with black. Let's stay in scope.

**Pull request merged**
