### PR TITLE
Add doc about debugging ansible-navigator

### PR DESCRIPTION
**Pull request by shatakshiiii**
- Adds information about debugging ansible-navigator using Vscode.
- Examples around debugging *subcommands* in Navigator.

### CODE REVIEW

**Review by ssbarnea — CHANGES_REQUESTED** [review]
Add the docs in this repository, linking to your personal repo is not ok.

**Comment by shatakshiiii** [comment]
I moved the docs stuff to the main repo and added some examples of debugging subcommands.

**Review by ssbarnea — CHANGES_REQUESTED** [review]
This should be trimmed since we already included a settings.json in the repo. In fact I would recommend adding the launch.json too so we reduce the amount of manual steps needed.

Part of writing the documentation includes changing our setup to reduce the amount of documentation we need to write. Makes sense?

**Comment by shatakshiiii** [comment]
> In fact I would recommend adding the launch.json too so we reduce the amount of manual steps needed.

Ahh, we have `launch.json` added in our repo with [PR](https://github.com/ansible/ansible-navigator/pull/1386).  Trimmed the content of doc a bit.

**Review by ssbarnea — APPROVED** [review]

**Comment by ssbarnea** [comment]
@cidrblock I think we are waiting for your review on this one.

**Review by cidrblock — APPROVED** [review]
awesome

**Pull request merged**
