### PR TITLE
[setup] ansible-runner: Pin to 2.0.0a2

### PR DESCRIPTION
**Pull request by Spredzy**
Depends-On: https://github.com/ansible/ansible-navigator/pull/257

### CODE REVIEW

**Comment by cidrblock** [comment]
(this most recent failure is porbably an issue with the version of setup tools installed)

**Comment by Spredzy** [comment]
recheck

**Comment by Spredzy** [comment]
Depends-On: https://github.com/ansible/ansible-navigator/pull/257

**Comment by cidrblock** [comment]
Recheck

**Review by cidrblock — APPROVED** [review]

**Pull request merged**
