### PR TITLE
Fix typing in `setup` of Sphinx spelling stub ext

### PR DESCRIPTION
**Pull request by webknjaz**

### CODE REVIEW

**Comment by webknjaz** [comment]
This PR does not attempt to fix the violation with `human_time()` because https://github.com/ansible/ansible-navigator/pull/641 will do this properly.

**Review by ssbarnea — APPROVED** [review]
LGTM, if we no longer see the error on pre-commit.ci, we merge it.

**Comment by webknjaz** [comment]
> 

I think there will still be an error with one function that is going to be addressed in another PR.

**Comment by ssbarnea** [comment]
> I think there will still be an error with one function that is going to be addressed in another PR.

Are you doing to address this error by any chance? I am asking because I find it bit funny that this error happens to raise from inside the "externally managed" file. If that is externally managed, I find hard to believe that the undocumented place where it comes from does not use mypy to check typing problems, especially as the file looks like being typed.

**Comment by webknjaz** [comment]
What are you talking about? What I mentioned was not related.

**Pull request merged**
