### PR TITLE
Integrate Towncrier

### PR DESCRIPTION
**Pull request by webknjaz**
Demo: https://ansible-navigator--654.org.readthedocs.build/en/654/changelog/#changelog.

Ref #558

### CODE REVIEW

**Comment by relrod** [comment]
recheck

**Review by ssbarnea — DISMISSED** [review]
Sorry but that is not what this project needs at this moment.

We need to finish enabling linting, passing unittests under GHA, adding code coverage and codecov and evaluate the release note creation after.

We should not put the cart before the horse.

**Comment by webknjaz** [comment]
> Sorry but that is not what this project needs at this moment.

This is _exactly_ what we agreed on in the previous discussions so I implemented it. It's as important as linting. Besides, I'm preparing the linting PR now too and this one is not blocked by that effort.

**Comment by cidrblock** [comment]
As long as we don't require change-log fragments or the use of the new label, this is fine for vetting and testing.

Please log issue to enable fragment required.

We cannot require changes to anyone dev workflow yet.

There is a chance, hopefully small, this gets reverted.

**Review by cidrblock — APPROVED** [review]

**Comment by webknjaz** [comment]
This got in via https://github.com/ansible/ansible-navigator/commit/4e333dea758c4225fc0192d2f1eb4f0084f0dbbf (apparently Zuul does not do proper merges).

**Comment by webknjaz** [comment]
> As long as we don't require change-log fragments (use of the new label), this is fine for vetting and testing.
> 
> Please log issue to enable fragment required.

I believe it is #558 — do we need another one or is this enough?

> We cannot require changes to anyone dev workflow yet.

Yep, while the check is present, if somebody won't want/be able to add a change note, I'll do it for them or apply `bot:chronographer:provided` so it does not block _anyone_ on this stage.

> There is a chance, hopefully small, this gets reverted.

Yep, we explicitly agreed on this.

**Pull request closed without merging**
