### PR TITLE
Note use of stdout for vars prompt in the FAQ

### PR DESCRIPTION
**Pull request by cidrblock**
Fixes https://github.com/ansible/ansible-navigator/issues/524

and a few spelling errors

### CODE REVIEW

**Comment by cidrblock** [comment]
recheck

**Comment by cidrblock** [comment]
recheck

**Comment by cidrblock** [comment]
recheck

**Comment by cidrblock** [comment]
recheck

**Review by ganeshrn — APPROVED** [review]

**Comment by cidrblock** [comment]
recheck

**Pull request merged**
