### PR TITLE
Resyncing with `main` pre- alpha2 release

### PR DESCRIPTION
**Pull request by Spredzy**

### CODE REVIEW

**Review by simaishi — APPROVED** [review]

**Comment by cidrblock** [comment]
This cannot merge until a PR locking navigator to runner A4 is in.

**Comment by cidrblock** [comment]
requires #430

**Comment by simaishi** [comment]
@cidrblock is this PR good to go? I tried to re-sync this PR to the latest main branch since a few more PRs went in since, but it doesn't look I can update this... so I'll open a new PR for the rest of the backports.

**Comment by simaishi** [comment]
Added recently merged PRs to this and opened a new PR https://github.com/ansible/ansible-navigator/pull/447, closing.

**Pull request closed without merging**
