### PR TITLE
Add more configuration entry in vscode settings

### PR DESCRIPTION
**Pull request by shatakshiiii**
- This PR adds example configuration to debug ansible-navigator subcommands.
- Example of debugging `exec` subcommand is mentioned.

### CODE REVIEW

**Comment by cidrblock** [comment]
The one I added is for debugging tests.. Did you mena to add an additional entry for just pure debugging?

```
 {
      "name": "ansible-navigator",
      "type": "python",
      "request": "launch",
      "module": "ansible_navigator",
      "args": ["exec", "--", "pwd"],
      "cwd": "${workspaceFolder}",
      "justMyCode": false
    }
```
somehting like that? ^

**Comment by shatakshiiii** [comment]
> The one I added is for debugging tests.. Did you mean to add an additional entry for just pure debugging?
> 
> ```
>  {
>       "name": "ansible-navigator",
>       "type": "python",
>       "request": "launch",
>       "module": "ansible_navigator",
>       "args": ["exec", "--", "pwd"],
>       "cwd": "${workspaceFolder}",
>       "justMyCode": false
>     }
> ```
> 
> somehting like that? ^

Yes, I tried adding exact piece as an additional configuration, but somehow the "Debug tests" wasn't working just as it is for me. Although not sure if this is the correct way of doing this. If not I can remove this, as we will have these  information as a document with [PR](https://github.com/ansible/ansible-navigator/pull/1377).

**Comment by ssbarnea** [comment]
Please don't add comments in JSON as we are never sure if these will work or not and editing the file using vscode UI will also break them.

For optional stuff, you can always add extra commands in addition to default "debug" one.

**Comment by cidrblock** [comment]
Aren't the comments fine?  I thought vscode fully supported JSONC for these files:

https://code.visualstudio.com/docs/languages/json#_json-with-comments

**Comment by ssbarnea** [comment]
They work here but what happens when you try to add an new entry? Also the comments here are not visible to the user in vscode which makes them kinda useless.

I was proposing adding the current commented example as a permanent run/debug configuration instead of a comment, at least users will be able to run the "pwd" and the "customization" is a no brainer when you see the extra launcher.

Basically we would "document" it w/o writing comments, and making that visible in vscode UI.

**Comment by cidrblock** [comment]
ah! yes let's add individual entries, I think that is a great idea

**Review by cidrblock — APPROVED** [review]

**Pull request merged**
