### PR TITLE
WIP: Create ansible-navigator-tox-py38 job

### PR DESCRIPTION
**Pull request by pabelanger**
This moves in-tree the tox-py38 job to make it easier for others to maintain.

Signed-off-by: Paul Belanger <pabelanger@redhat.com>
Depends-On: https://github.com/ansible/ansible-zuul-jobs/pull/1100

### CODE REVIEW

**Comment by pabelanger** [comment]
recheck

**Comment by pabelanger** [comment]
Pull-request updated, HEAD is now 9df9ae49cd336b0beda369f2c44d30e5eaf8fe69

**Comment by pabelanger** [comment]
Pull-request updated, HEAD is now c3bde6f95d82064c1db15271d663643b7e64752f

**Comment by ssbarnea** [comment]
Already done.

**Pull request closed without merging**
