### PR TITLE
Update __task when runner event is in `ok`, `skipped`, `unreachable` and `failed` state

### LINKED ISSUE #541: Tasks names do not resolve variables
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
Tasks names in Navigator do not resolve variables.

##### ANSIBLE-NAVIGATOR VERSION

```bash
⇨  ansible-navigator --version
ansible-navigator 1.0.0

```

##### CONFIGURATION

[ansible-navigator.yml](https://github.com/nleiva/ansible-kubernetes/blob/main/ansible-navigator.yml)

##### STEPS TO REPRODUCE

Create a task with a variable on its name. For [example](https://github.com/nleiva/ansible-kubernetes/blob/main/roles/install_dependencies/tasks/main.yml#L1):

```yaml
- name: Install Python dependencies for {{ cloud_provider }}
  ansible.builtin.pip:
    ...
```

##### EXPECTED RESULTS

```bash
TASK [install_dependencies : Install Python dependencies for aws]
```

##### ACTUAL RESULTS

```bash
TASK [install_dependencies : Install Python dependencies for {{ cloud_provider }}]
```

### PR DESCRIPTION
**Pull request by priyamsahoo**
- Resolves #541
- Includes additional tests for the same

### CODE REVIEW

**Comment by cidrblock** [comment]
recheck

**Comment by cidrblock** [comment]
recheck

**Comment by cidrblock** [comment]
recheck

**Comment by cidrblock** [comment]
recheck

**Comment by cidrblock** [comment]
recheck

**Comment by cidrblock** [comment]
recheck

**Comment by cidrblock** [comment]
gate on behalf of @priyamsahoo

**Comment by priyamsahoo** [comment]
> gate on behalf of @priyamsahoo

Thank you @cidrblock :)

**Pull request merged**
