### PR TITLE
Revert "Drop `{tty}` and `{temp_dir}` substitutions"

### PR DESCRIPTION
**Pull request by webknjaz**
This reverts commit 48601e8df49c5240aad5ee96cf9b9bce7e8a50cb.

Depends-On: https://github.com/ansible/ansible-navigator/pull/571

### CODE REVIEW

**Comment by relrod** [comment]
recheck

**Comment by relrod** [comment]
recheck

**Comment by webknjaz** [comment]
@pabelanger could you check why this still uses old tox?

**Comment by webknjaz** [comment]
recheck

**Comment by webknjaz** [comment]
recheck

**Review by ssbarnea — APPROVED** [review]

**Comment by ssbarnea** [comment]
recheck

**Pull request merged**
