### PR TITLE
[config] micro optimization as suggested

### PR DESCRIPTION
**Pull request by cidrblock**
depends-on: https://github.com/ansible/ansible-navigator/pull/257

thx @relrod ! 

closes #229

### CODE REVIEW

**Comment by cidrblock** [comment]
recheck

**Review by relrod — APPROVED** [review]

**Comment by cidrblock** [comment]
recheck

**Comment by cidrblock** [comment]
recheck

**Comment by cidrblock** [comment]
recheck

**Comment by cidrblock** [comment]
recheck

**Comment by cidrblock** [comment]
recheck

**Pull request merged**
