### PR TITLE
CommandAsync should not discard event

### LINKED ISSUE #1435: playbook-artifact-enable prevents job_events json files from being created in the ansible-runner-artifact-dir
##### ISSUE TYPE

- Bug Report

##### SUMMARY

When the playbook artifact is enabled ( --pae true ) the ansible-runner-artifact-dir ( --rad ) does not contain the expected job_events json files.

##### ANSIBLE-NAVIGATOR VERSION

```
ansible-navigator 2.2.0
```

##### CONFIGURATION

no config files or env vars

##### LOG FILE

no log generated

##### STEPS TO REPRODUCE

Remove any existing artifact directory from working directory
``` 
rm -r artifacts
```
Run ansible playbook in stdout mode with --rad configured to the current directory and --pae enabled. 
```
ansible-navigator run playbook.yml -i localhost, -m stdout --ee false --rad . --pae true
```

##### EXPECTED RESULTS

There should be json files in the job_events directory for events generated during the play.
For a working example set ( --pae false)  and see the json files created in the job_events directory. 
```
$ ansible-navigator run playbook.yml -i localhost, -m stdout --ee false --rad .  --pae false

PLAY [all] ***************************************************************************************************************************

TASK [Gathering Facts] ***************************************************************************************************************
ok: [localhost]

TASK [touch file] ********************************************************************************************************************
changed: [localhost]

PLAY RECAP ***************************************************************************************************************************
localhost                  : ok=2    changed=1    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0   

$ find artifacts/ -name '*.json'
artifacts/93ac8fb0-6a40-49fc-872c-d19799bbfc6f/job_events/c1d3bda8-5968-4def-8d83-7da1f62129fd-partial.json
artifacts/93ac8fb0-6a40-49fc-872c-d19799bbfc6f/job_events/005056b6-64e8-6a3c-96c7-000000000006-partial.json
artifacts/93ac8fb0-6a40-49fc-872c-d19799bbfc6f/job_events/005056b6-64e8-6a3c-96c7-00000000000c-partial.json
artifacts/93ac8fb0-6a40-49fc-872c-d19799bbfc6f/job_events/c10433fe-6c62-4d82-896c-9a997411a19d-partial.json
artifacts/93ac8fb0-6a40-49fc-872c-d19799bbfc6f/job_events/99a1dd38-3ef4-4ae3-b85d-b199edcf14cd-partial.json
artifacts/93ac8fb0-6a40-49fc-872c-d19799bbfc6f/job_events/005056b6-64e8-6a3c-96c7-000000000008-partial.json
artifacts/93ac8fb0-6a40-49fc-872c-d19799bbfc6f/job_events/8118746c-625f-478b-beba-f017d21fc133-partial.json
artifacts/93ac8fb0-6a40-49fc-872c-d19799bbfc6f/job_events/5cf71e6b-82bf-4555-a4a5-b3b050df349a-partial.json
artifacts/93ac8fb0-6a40-49fc-872c-d19799bbfc6f/job_events/33891465-45af-47a6-835b-1c2224c21b06-partial.json
```

##### ACTUAL RESULTS

There are no json files written in the job_events directory. 
```
$ find artifacts/
artifacts/
artifacts/14436137-4bf5-4d58-a396-4da5ba1f5999
artifacts/14436137-4bf5-4d58-a396-4da5ba1f5999/job_events
artifacts/14436137-4bf5-4d58-a396-4da5ba1f5999/command
artifacts/14436137-4bf5-4d58-a396-4da5ba1f5999/stdout
artifacts/14436137-4bf5-4d58-a396-4da5ba1f5999/stderr
artifacts/14436137-4bf5-4d58-a396-4da5ba1f5999/fact_cache
artifacts/14436137-4bf5-4d58-a396-4da5ba1f5999/fact_cache/localhost
artifacts/14436137-4bf5-4d58-a396-4da5ba1f5999/status
artifacts/14436137-4bf5-4d58-a396-4da5ba1f5999/rc
```

##### ADDITIONAL INFORMATION

When (--pae true) the ansible-playbook command is running using `ansible_navigator/runner/command_async.py` 
I think the CommandAsync _event_handler should be returning true so that ansible-runner will process the events too and generate the expected job_events artifacts. I tried this modification and it seemed to work. 

```
--- site-packages/ansible_navigator/runner/command_async.py	2023-02-02 16:14:07.170140090 -0500
+++ ~/command_async.py	2023-02-07 09:27:16.810296832 -0500
@@ -33,6 +33,7 @@
         self._logger.debug("ansible-runner event handle: %s", event)
         new_event = deepcopy(event)
         self._queue.put(new_event)
+        return True
 
     def run(self):
         """Initiate the execution of the runner command in async mode.
```

### PR DESCRIPTION
**Pull request by eamigo**
The CommandAsync _event_handler function should return True to keep the event, otherwise it will be discarded by ansible-runner. https://ansible-runner.readthedocs.io/en/stable/python_interface/#runner-event-handler

Fixes #1435

### CODE REVIEW

**Comment by ssbarnea** [comment]
I am afraid that you will need to rebase this one.

**Comment by shatakshiiii** [comment]
> I am afraid that you will need to rebase this one.

Ahh, those confilcts. I will check this PR locally.

**Comment by shatakshiiii** [comment]
Ahh, those conflicts. I will check this PR locally :)

**Comment by cidrblock** [comment]
Sorry about the sloppy rebase, I accidentally pushed some merge conflicts and had a heck of a time cleaning up my mess.

**Review by cidrblock — APPROVED** [review]

**Comment by cidrblock** [comment]
@eamigo Just wanted to take a minute to thank you for the PRs. navigator has a "tricky?" code base and you did some cool stuff.  If you have any suggestions about your dev or testing experience with it, we'd love to hear from you.

**Pull request merged**
